/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package playlist;

import java.awt.Image;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author juluc
 */
public class Ventana extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana.class.getName());

    /**
     * Creates new form Ventana
     */
    private Controlador manager;
private enum Estado { PARADO, REPRODUCIENDO, PAUSADO }
private Estado estado = Estado.PARADO;
    public Ventana(Controlador manager) {
        this.manager = manager;
        initComponents();
        labelGif.setVisible(false);
       
        ImageIcon iconPlay = new ImageIcon(getClass().getResource("/Images/play.png"));
        Image imgPlay = iconPlay.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
        buttonPlay.setIcon(new ImageIcon(imgPlay));
        buttonPlay.setText(""); // quita el texto si solo quieres el icono

        ImageIcon iconNext = new ImageIcon(getClass().getResource("/Images/next.png"));
        Image imgNext = iconNext.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
        buttonNext.setIcon(new ImageIcon(imgNext));
        buttonNext.setText("");

        ImageIcon iconPrev = new ImageIcon(getClass().getResource("/Images/prev.png"));
        Image imgPrev = iconPrev.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
        buttonprev.setIcon(new ImageIcon(imgPrev));
        buttonprev.setText("");
        
    }



    public void actualizarJList(Controlador manager) {
           DefaultListModel<String> modelo = new DefaultListModel<>();
    for (String nombre : manager.getNombresParaLista()) {
        modelo.addElement(nombre);
    }
    listMusic.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPlay = new javax.swing.JButton();
        buttonNext = new javax.swing.JButton();
        buttonprev = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMusic = new javax.swing.JList<>();
        labelGif = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonLoad = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Btnultimo = new javax.swing.JButton();
        BtnPrimero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonPlay.setText("Play/Stop");
        buttonPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPlayMouseClicked(evt);
            }
        });

        buttonNext.setText("Next");
        buttonNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNextMouseClicked(evt);
            }
        });

        buttonprev.setText("Anterior");
        buttonprev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonprevMouseClicked(evt);
            }
        });

        listMusic.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listMusic);

        labelGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/playing.gif"))); // NOI18N
        labelGif.setText("s");

        jLabel2.setText("Music Player");

        buttonLoad.setText("Load");
        buttonLoad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLoadMouseClicked(evt);
            }
        });

        jLabel3.setText("z");

        Btnultimo.setText("ultimo");
        Btnultimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnultimoMouseClicked(evt);
            }
        });

        BtnPrimero.setText("Primero");
        BtnPrimero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnPrimero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPrimeroMouseClicked(evt);
            }
        });
        BtnPrimero.addActionListener(this::BtnPrimeroActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnPrimero)
                        .addGap(47, 47, 47)
                        .addComponent(buttonprev)
                        .addGap(58, 58, 58)
                        .addComponent(buttonPlay)
                        .addGap(69, 69, 69)
                        .addComponent(buttonNext)
                        .addGap(51, 51, 51)
                        .addComponent(Btnultimo))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(labelGif, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(buttonLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelGif, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPlay)
                    .addComponent(buttonNext)
                    .addComponent(buttonprev)
                    .addComponent(Btnultimo)
                    .addComponent(BtnPrimero))
                .addGap(30, 30, 30)
                .addComponent(jLabel3))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLoadMouseClicked
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = chooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String ruta = chooser.getSelectedFile().getAbsolutePath();
            manager.cargarDesdeCarpeta(ruta);
            this.actualizarJList(manager); // Refresca la lista visualmente
        }
    }//GEN-LAST:event_buttonLoadMouseClicked

    private void buttonprevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonprevMouseClicked
    manager.anterior();
  estado = Estado.REPRODUCIENDO;
        labelGif.setVisible(true);
       
        
    }//GEN-LAST:event_buttonprevMouseClicked

    private void buttonPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPlayMouseClicked
           switch (estado) {
        case PARADO:
            manager.iniciar();
            estado = Estado.REPRODUCIENDO;
            labelGif.setVisible(true);
            
            break;
        case REPRODUCIENDO:
            manager.pausar();
            estado = Estado.PAUSADO;
            labelGif.setVisible(false);
      
            break;
        case PAUSADO:
            manager.reanudar();
            estado = Estado.REPRODUCIENDO;
            labelGif.setVisible(true);
            
            break;
    }
    }//GEN-LAST:event_buttonPlayMouseClicked

    private void buttonNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNextMouseClicked
        manager.siguiente();
  estado = Estado.REPRODUCIENDO;
        labelGif.setVisible(true);
      
    }//GEN-LAST:event_buttonNextMouseClicked

    private void BtnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrimeroActionPerformed
        // T
    }//GEN-LAST:event_BtnPrimeroActionPerformed

    private void BtnPrimeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPrimeroMouseClicked
      manager.primero();
      estado = Estado.REPRODUCIENDO;
      labelGif.setVisible(true);
    }//GEN-LAST:event_BtnPrimeroMouseClicked

    private void BtnultimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnultimoMouseClicked
      manager.ultimo();
      estado = Estado.REPRODUCIENDO;
      labelGif.setVisible(true);
    }//GEN-LAST:event_BtnultimoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        // ↓ Crea el controlador aquí para poder pasarlo al constructor
        java.awt.EventQueue.invokeLater(() -> {
            Lista_DEC lista = new Lista_DEC();
            Controlador ctrl = new Controlador(lista);
            new Ventana(ctrl).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPrimero;
    private javax.swing.JButton Btnultimo;
    private javax.swing.JButton buttonLoad;
    private javax.swing.JButton buttonNext;
    private javax.swing.JButton buttonPlay;
    private javax.swing.JButton buttonprev;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelGif;
    private javax.swing.JList<String> listMusic;
    // End of variables declaration//GEN-END:variables
}
